default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: things_matter_development

test:
  <<: *default
  database: things_matter_test

production:
  <<: *default
  database: things_matter_production
  username: things_matter
  password: <%= ENV['GRAPHQL_MEETUP_DATABASE_PASSWORD'] %>
